package com.helpdesk.capacitacionjava.modelos;
// Generated 13-ene-2020 16:42:31 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bitacora generated by hbm2java
 */
@Entity
@Table(name="bitacora"
    ,schema="public"
)
public class Bitacora  implements java.io.Serializable {


     private int bitaId;
     private Date bitaFecha;
     private Date bitaHora;
     private String bitaTabla;
     private String bitaTipo;
     private String bitaUsuario;

    public Bitacora() {
    }

	
    public Bitacora(int bitaId, Date bitaFecha, String bitaUsuario) {
        this.bitaId = bitaId;
        this.bitaFecha = bitaFecha;
        this.bitaUsuario = bitaUsuario;
    }
    public Bitacora(int bitaId, Date bitaFecha, Date bitaHora, String bitaTabla, String bitaTipo, String bitaUsuario) {
       this.bitaId = bitaId;
       this.bitaFecha = bitaFecha;
       this.bitaHora = bitaHora;
       this.bitaTabla = bitaTabla;
       this.bitaTipo = bitaTipo;
       this.bitaUsuario = bitaUsuario;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tbbitacora_idbitacora_seq")
    @javax.persistence.SequenceGenerator(
            name = "tbbitacora_idbitacora_seq",
            sequenceName = "tbbitacora_idbitacora_seq",
            allocationSize = 1
    )

    
    @Column(name="bita_id", unique=true, nullable=false)
    public int getBitaId() {
        return this.bitaId;
    }
    
    public void setBitaId(int bitaId) {
        this.bitaId = bitaId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bita_fecha", nullable=false, length=13)
    public Date getBitaFecha() {
        return this.bitaFecha;
    }
    
    public void setBitaFecha(Date bitaFecha) {
        this.bitaFecha = bitaFecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="bita_hora", length=15)
    public Date getBitaHora() {
        return this.bitaHora;
    }
    
    public void setBitaHora(Date bitaHora) {
        this.bitaHora = bitaHora;
    }

    
    @Column(name="bita_tabla", length=100)
    public String getBitaTabla() {
        return this.bitaTabla;
    }
    
    public void setBitaTabla(String bitaTabla) {
        this.bitaTabla = bitaTabla;
    }

    
    @Column(name="bita_tipo", length=100)
    public String getBitaTipo() {
        return this.bitaTipo;
    }
    
    public void setBitaTipo(String bitaTipo) {
        this.bitaTipo = bitaTipo;
    }

    
    @Column(name="bita_usuario", nullable=false, length=100)
    public String getBitaUsuario() {
        return this.bitaUsuario;
    }
    
    public void setBitaUsuario(String bitaUsuario) {
        this.bitaUsuario = bitaUsuario;
    }




}


