package com.helpdesk.capacitacionjava.modelos;
// Generated 13-ene-2020 16:42:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Continentes generated by hbm2java
 */
@Entity
@Table(name="continentes"
    ,schema="public"
)
public class Continentes  implements java.io.Serializable {


     private int contiId;
     private String contiNombre;
     private Set<Paises> paiseses = new HashSet<Paises>(0);

    public Continentes() {
    }

	
    public Continentes(int contiId, String contiNombre) {
        this.contiId = contiId;
        this.contiNombre = contiNombre;
    }
    public Continentes(int contiId, String contiNombre, Set<Paises> paiseses) {
       this.contiId = contiId;
       this.contiNombre = contiNombre;
       this.paiseses = paiseses;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tbcontinente_idcontinente_seq")
    @javax.persistence.SequenceGenerator(
            name = "tbcontinente_idcontinente_seq",
            sequenceName = "tbcontinente_idcontinente_seq",
            allocationSize = 1
    )
    
    @Column(name="conti_id", unique=true, nullable=false)
    public int getContiId() {
        return this.contiId;
    }
    
    public void setContiId(int contiId) {
        this.contiId = contiId;
    }

    
    @Column(name="conti_nombre", nullable=false, length=10)
    public String getContiNombre() {
        return this.contiNombre;
    }
    
    public void setContiNombre(String contiNombre) {
        this.contiNombre = contiNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="continentes")
    public Set<Paises> getPaiseses() {
        return this.paiseses;
    }
    
    public void setPaiseses(Set<Paises> paiseses) {
        this.paiseses = paiseses;
    }




}


