package com.helpdesk.capacitacionjava.modelos;
// Generated 13-ene-2020 16:42:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamentos generated by hbm2java
 */
@Entity
@Table(name="departamentos"
    ,schema="public"
)
public class Departamentos  implements java.io.Serializable {


     private int depId;
     private Paises paises;
     private String depCabecera;
     private Double depExtension;
     private String depNombre;
     private Set<Zonas> zonases = new HashSet<Zonas>(0);

    public Departamentos() {
    }

	
    public Departamentos(int depId, Paises paises, String depNombre) {
        this.depId = depId;
        this.paises = paises;
        this.depNombre = depNombre;
    }
    public Departamentos(int depId, Paises paises, String depCabecera, Double depExtension, String depNombre, Set<Zonas> zonases) {
       this.depId = depId;
       this.paises = paises;
       this.depCabecera = depCabecera;
       this.depExtension = depExtension;
       this.depNombre = depNombre;
       this.zonases = zonases;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tbDepartamento_iddepartamento_seq")
    @javax.persistence.SequenceGenerator(
            name = "tbDepartamento_iddepartamento_seq",
            sequenceName = "tbDepartamento_iddepartamento_seq",
            allocationSize = 1
    )
    
    @Column(name="dep_id", unique=true, nullable=false)
    public int getDepId() {
        return this.depId;
    }
    
    public void setDepId(int depId) {
        this.depId = depId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pais_id", nullable=false)
    public Paises getPaises() {
        return this.paises;
    }
    
    public void setPaises(Paises paises) {
        this.paises = paises;
    }

    
    @Column(name="dep_cabecera", length=50)
    public String getDepCabecera() {
        return this.depCabecera;
    }
    
    public void setDepCabecera(String depCabecera) {
        this.depCabecera = depCabecera;
    }

    
    @Column(name="dep_extension", precision=17, scale=17)
    public Double getDepExtension() {
        return this.depExtension;
    }
    
    public void setDepExtension(Double depExtension) {
        this.depExtension = depExtension;
    }

    
    @Column(name="dep_nombre", nullable=false, length=75)
    public String getDepNombre() {
        return this.depNombre;
    }
    
    public void setDepNombre(String depNombre) {
        this.depNombre = depNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamentos")
    public Set<Zonas> getZonases() {
        return this.zonases;
    }
    
    public void setZonases(Set<Zonas> zonases) {
        this.zonases = zonases;
    }




}


