package com.helpdesk.capacitacionjava.modelos;
// Generated 13-ene-2020 16:42:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paises generated by hbm2java
 */
@Entity
@Table(name="paises"
    ,schema="public"
)
public class Paises  implements java.io.Serializable {


     private int paisId;
     private Continentes continentes;
     private String paisNombre;
     private Set<Departamentos> departamentoses = new HashSet<Departamentos>(0);

    public Paises() {
    }

	
    public Paises(int paisId, Continentes continentes, String paisNombre) {
        this.paisId = paisId;
        this.continentes = continentes;
        this.paisNombre = paisNombre;
    }
    public Paises(int paisId, Continentes continentes, String paisNombre, Set<Departamentos> departamentoses) {
       this.paisId = paisId;
       this.continentes = continentes;
       this.paisNombre = paisNombre;
       this.departamentoses = departamentoses;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tbPaises_idpaises_seq")
    @javax.persistence.SequenceGenerator(
            name = "tbPaises_idpaises_seq",
            sequenceName = "tbPaises_idpaises_seq",
            allocationSize = 1
    )
    
    @Column(name="pais_id", unique=true, nullable=false)
    public int getPaisId() {
        return this.paisId;
    }
    
    public void setPaisId(int paisId) {
        this.paisId = paisId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="conti_id", nullable=false)
    public Continentes getContinentes() {
        return this.continentes;
    }
    
    public void setContinentes(Continentes continentes) {
        this.continentes = continentes;
    }

    
    @Column(name="pais_nombre", nullable=false, length=30)
    public String getPaisNombre() {
        return this.paisNombre;
    }
    
    public void setPaisNombre(String paisNombre) {
        this.paisNombre = paisNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paises")
    public Set<Departamentos> getDepartamentoses() {
        return this.departamentoses;
    }
    
    public void setDepartamentoses(Set<Departamentos> departamentoses) {
        this.departamentoses = departamentoses;
    }




}


