package com.helpdesk.capacitacionjava.modelos;
// Generated 13-ene-2020 16:42:31 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Zonas generated by hbm2java
 */
@Entity
@Table(name="zonas"
    ,schema="public"
)
public class Zonas  implements java.io.Serializable {


     private int zonaId;
     private Departamentos departamentos;
     private String zonaDescripcion;
     private String zonaNombre;

    public Zonas() {
    }

	
    public Zonas(int zonaId, Departamentos departamentos, String zonaNombre) {
        this.zonaId = zonaId;
        this.departamentos = departamentos;
        this.zonaNombre = zonaNombre;
    }
    public Zonas(int zonaId, Departamentos departamentos, String zonaDescripcion, String zonaNombre) {
       this.zonaId = zonaId;
       this.departamentos = departamentos;
       this.zonaDescripcion = zonaDescripcion;
       this.zonaNombre = zonaNombre;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tbzonas_idzonas_seq")
    @javax.persistence.SequenceGenerator(
            name = "tbzonas_idzonas_seq",
            sequenceName = "tbzonas_idzonas_seq",
            allocationSize = 1
    )
    
    @Column(name="zona_id", unique=true, nullable=false)
    public int getZonaId() {
        return this.zonaId;
    }
    
    public void setZonaId(int zonaId) {
        this.zonaId = zonaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dep_id", nullable=false)
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }

    
    @Column(name="zona_descripcion", length=200)
    public String getZonaDescripcion() {
        return this.zonaDescripcion;
    }
    
    public void setZonaDescripcion(String zonaDescripcion) {
        this.zonaDescripcion = zonaDescripcion;
    }

    
    @Column(name="zona_nombre", nullable=false, length=50)
    public String getZonaNombre() {
        return this.zonaNombre;
    }
    
    public void setZonaNombre(String zonaNombre) {
        this.zonaNombre = zonaNombre;
    }




}


